"""Environment-driven settings.

The split between this module and :mod:`config` is deliberate:

* ``settings`` is what changes between a laptop, staging and production —
  credentials, hosts, timeouts, whether to run headless.
* ``config`` is what is true about the DOE dashboard itself regardless of where
  the scraper runs.

Anything secret belongs here and only here, so it can be supplied by the
environment and never read from a checked-in file.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from urllib.parse import quote_plus

from pydantic import Field, computed_field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

BASE_DIR = Path(__file__).resolve().parent


class Settings(BaseSettings):
    """Runtime configuration, read from the environment or a local ``.env``."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_prefix="DOE_",
        extra="ignore",
    )

    # --- database -----------------------------------------------------------
    db_host: str = Field(default="127.0.0.1")
    db_port: int = Field(default=3306)
    # Its own database, not the platform's. FIP's Laravel migrations already
    # own a `fuel_price_history` with an incompatible shape (one row per fuel
    # type, against one row per station-date here), so the two must not share a
    # schema. The bridge command in the backend is what moves rows across.
    db_name: str = Field(default="fip_doe")
    db_user: str = Field(default="fip")
    db_password: str = Field(default="")
    db_charset: str = Field(default="utf8mb4")

    # SQLAlchemy recycles connections before MySQL's wait_timeout (8h by
    # default) drops them. A daily scraper holding a pool overnight is exactly
    # the case that produces "MySQL server has gone away" on the next run.
    db_pool_recycle: int = Field(default=3600)
    db_pool_pre_ping: bool = Field(default=True)
    db_echo: bool = Field(default=False)

    # --- dashboard ----------------------------------------------------------
    dashboard_url: str = Field(
        default=(
            "https://lookerstudio.google.com/embed/reporting/"
            "e7cbb3b1-c1d2-4c8b-9d1e-000000000000/page/p_doe_prices"
        ),
        description=(
            "Full Looker Studio report URL. Override per environment — the "
            "DOE re-publishes under a new report id when the dashboard is "
            "rebuilt."
        ),
    )

    # --- browser ------------------------------------------------------------
    headless: bool = Field(default=True)
    browser_timeout_ms: int = Field(default=90_000)
    # How long to keep listening after the page reports network idle. Looker
    # fires additional batchedDataV2 calls as tiles lazily render, and the last
    # one routinely lands several seconds after load completes.
    settle_timeout_ms: int = Field(default=20_000)
    user_agent: str = Field(
        default=(
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like "
            "Gecko) Chrome/131.0.0.0 Safari/537.36"
        )
    )
    viewport_width: int = Field(default=1920)
    viewport_height: int = Field(default=1080)

    # --- run behaviour ------------------------------------------------------
    max_attempts: int = Field(default=3, ge=1)
    retry_base_delay_s: float = Field(default=5.0, ge=0)
    schedule_hour: int = Field(default=6, ge=0, le=23)
    schedule_minute: int = Field(default=0, ge=0, le=59)
    timezone: str = Field(default="Asia/Manila")

    # --- observability ------------------------------------------------------
    log_level: str = Field(default="INFO")
    log_json: bool = Field(default=False)
    log_dir: Path = Field(default=BASE_DIR / "logs")
    # Raw intercepted payloads, kept for replay when a run parses to zero rows.
    capture_dir: Path = Field(default=BASE_DIR / "captures")
    capture_payloads: bool = Field(default=True)
    capture_retention_days: int = Field(default=14)

    @field_validator("log_level")
    @classmethod
    def _upper(cls, value: str) -> str:
        return value.upper()

    @computed_field  # type: ignore[prop-decorator]
    @property
    def database_url(self) -> str:
        """SQLAlchemy URL.

        The password is quoted because MySQL passwords generated by a secrets
        manager routinely contain ``@`` and ``/``, which silently truncate an
        unquoted DSN into a connection to the wrong host.
        """
        password = quote_plus(self.db_password)
        return (
            f"mysql+pymysql://{self.db_user}:{password}"
            f"@{self.db_host}:{self.db_port}/{self.db_name}"
            f"?charset={self.db_charset}"
        )

    def safe_database_url(self) -> str:
        """The DSN with the password removed, for logs."""
        return f"mysql+pymysql://{self.db_user}:***@{self.db_host}:{self.db_port}/{self.db_name}"


@lru_cache
def get_settings() -> Settings:
    """Cached settings singleton."""
    return Settings()
