<?php

declare(strict_types=1);

namespace App\Domain\Fleet\Services;

use App\Domain\User\Models\AuditLog;
use App\Domain\User\Models\User;
use App\Domain\User\Models\UserDevice;
use App\Domain\Vehicle\Models\Vehicle;
use App\Support\Exceptions\DomainException;
use Illuminate\Support\Facades\DB;

/**
 * Registration and lifecycle for devices that report vehicle location.
 *
 * The identifier is generated by the application and stored on the device, not
 * read from the hardware. Both platforms have spent years making real hardware
 * identifiers unavailable or unstable — Android rotates the advertising ID and
 * gates the IMEI behind privileged permissions, iOS returns a per-vendor value
 * that resets when the last app from that vendor is deleted — and an installation
 * identifier is the honest version of what those APIs used to provide. It is also
 * the thing the app already has: the mobile client has persisted one in secure
 * storage and sent it as `X-Device-Id` on every request since long before this
 * feature existed.
 *
 * Registration is idempotent on `(user_id, device_uuid)`, because a reinstall
 * that generates a new identifier should produce a new row, while a relaunch
 * that reuses the stored one should not.
 */
final readonly class DeviceRegistrationService
{
    /**
     * Register, or refresh, the calling user's device.
     *
     * `user_id` comes from the authenticated session and never from the body.
     * A client can name its device; it cannot say whose it is.
     *
     * @param array{device_uuid: string, platform: string, device_name?: string|null,
     *              app_version?: string|null, os_version?: string|null,
     *              fcm_token?: string|null} $data
     */
    public function register(User $user, array $data): UserDevice
    {
        $existing = UserDevice::query()
            ->where('user_id', $user->getKey())
            ->where('device_uuid', $data['device_uuid'])
            ->first();

        // A revoked registration is not silently resurrected by reinstalling.
        // Whoever revoked it did so for a reason, and the device coming back
        // asking politely is not new information.
        if ($existing !== null && $existing->isRevoked()) {
            throw new DomainException(
                'This device has been revoked. Ask an administrator to restore it.',
                'device_revoked',
                403,
            );
        }

        $device = UserDevice::updateOrCreate(
            ['user_id' => $user->getKey(), 'device_uuid' => $data['device_uuid']],
            [
                'platform' => $data['platform'],
                'device_name' => $data['device_name'] ?? null,
                'app_version' => $data['app_version'] ?? null,
                'os_version' => $data['os_version'] ?? null,
                'fcm_token' => $data['fcm_token'] ?? null,
                'last_seen_at' => now(),
            ],
        );

        $this->audit($device, $device->wasRecentlyCreated ? 'device_registered' : 'device_refreshed', [
            'platform' => $device->platform,
            'app_version' => $device->app_version,
        ]);

        return $device;
    }

    /**
     * Point a device at a vehicle.
     *
     * Two authorisations are required and the caller must have proved both
     * before reaching here: `update` on the device (it is their handset) and
     * `update` on the vehicle (they are entitled to that vehicle). Checking
     * only the first would let any driver attach themselves to any truck.
     *
     * One active device per vehicle: a second registration displaces the first
     * rather than joining it, because two devices reporting for one vehicle
     * produce two interleaved tracks and no way to say which is the vehicle.
     */
    public function assignToVehicle(UserDevice $device, Vehicle $vehicle): UserDevice
    {
        if ($device->isRevoked()) {
            throw new DomainException(
                'A revoked device cannot be assigned to a vehicle.',
                'device_revoked',
                403,
            );
        }

        return DB::transaction(function () use ($device, $vehicle): UserDevice {
            $displaced = UserDevice::query()
                ->active()
                ->where('vehicle_id', $vehicle->getKey())
                ->where('id', '!=', $device->getKey())
                ->get();

            foreach ($displaced as $other) {
                $other->forceFill(['vehicle_id' => null])->save();

                $this->audit($other, 'device_vehicle_detached', [
                    'vehicle_id' => $vehicle->getKey(),
                    'reason' => 'displaced by a newer registration',
                ]);
            }

            $previous = $device->vehicle_id;
            $device->forceFill(['vehicle_id' => $vehicle->getKey()])->save();

            $this->audit($device, 'device_vehicle_assigned', [
                'vehicle_id' => $vehicle->getKey(),
                'plate_number' => $vehicle->plate_number,
                'previous_vehicle_id' => $previous,
                'displaced_devices' => $displaced->pluck('id')->all(),
            ]);

            return $device->refresh();
        });
    }

    /** Detach a device from its vehicle without revoking the registration. */
    public function detachFromVehicle(UserDevice $device): UserDevice
    {
        $previous = $device->vehicle_id;

        if ($previous === null) {
            return $device;
        }

        $device->forceFill(['vehicle_id' => null])->save();

        $this->audit($device, 'device_vehicle_detached', ['vehicle_id' => $previous]);

        return $device->refresh();
    }

    /**
     * Stop a device reporting, permanently.
     *
     * The row and its history stay: revocation answers "may this device write
     * from now on", not "did it ever exist". Deleting the history to revoke a
     * handset would destroy the record of where the vehicle went.
     */
    public function revoke(UserDevice $device, User $actor, ?string $reason = null): UserDevice
    {
        if ($device->isRevoked()) {
            return $device;
        }

        $device->forceFill([
            'revoked_at' => now(),
            'revoked_by' => $actor->getKey(),
            'vehicle_id' => null,
            'fcm_token' => null,   // stop push as well; the device is untrusted
        ])->save();

        $this->audit($device, 'device_revoked', [
            'revoked_by' => $actor->getKey(),
            'reason' => $reason,
        ]);

        return $device->refresh();
    }

    /**
     * Resolve the device behind a request.
     *
     * The pair, never the identifier alone: `X-Device-Id` is a value the client
     * supplies, so on its own it would let one authenticated user write
     * location as another's device simply by copying a header.
     */
    public function resolve(User $user, ?string $deviceUuid): ?UserDevice
    {
        if ($deviceUuid === null || $deviceUuid === '') {
            return null;
        }

        return UserDevice::query()
            ->where('user_id', $user->getKey())
            ->where('device_uuid', $deviceUuid)
            ->first();
    }

    /**
     * Device lifecycle events are written straight to the audit log rather than
     * through the Auditable trait. The trait records column diffs, which for a
     * revocation is a timestamp appearing — true, but not the point. These
     * events say what happened in terms a reviewer reads.
     */
    private function audit(UserDevice $device, string $event, array $context = []): void
    {
        $request = request();

        AuditLog::create([
            'user_id' => auth()->id(),
            'event' => $event,
            'auditable_type' => UserDevice::class,
            'auditable_id' => $device->getKey(),
            'new_values' => $context + ['device_id' => $device->getKey()],
            'url' => $request?->fullUrl(),
            'ip_address' => $request?->ip() ? inet_pton($request->ip()) : null,
            'user_agent' => substr((string) $request?->userAgent(), 0, 255) ?: null,
            'request_id' => $request?->attributes->get('request_id'),
        ]);
    }
}
