<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\V1;

use App\Domain\Reporting\Models\ReportDefinition;
use App\Domain\Reporting\Models\ReportRun;
use App\Domain\Reporting\Services\ReportService;
use App\Http\Controllers\Controller;
use App\Support\Exceptions\DomainException;
use App\Support\Http\ApiResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * @OA\Tag(name="Reports", description="Report generation and export")
 */
class ReportController extends Controller
{
    public function __construct(private readonly ReportService $reports) {}

    /**
     * @OA\Get(path="/reports/definitions", tags={"Reports"}, security={{"bearerAuth":{}}},
     *   summary="Reports the caller may run", @OA\Response(response=200, description="Definitions"))
     */
    public function definitions(Request $request): JsonResponse
    {
        $available = ReportDefinition::all()->filter(
            fn (ReportDefinition $d) => $d->required_permission === null || $request->user()->can($d->required_permission),
        )->values();

        return ApiResponse::success($available->all());
    }

    /**
     * @OA\Post(path="/reports/generate", tags={"Reports"}, security={{"bearerAuth":{}}},
     *   summary="Generate a report",
     *
     *   @OA\RequestBody(required=true, @OA\JsonContent(
     *     required={"code"},
     *
     *     @OA\Property(property="code", type="string", example="fuel_expense_summary"),
     *     @OA\Property(property="format", type="string", enum={"pdf","xlsx","csv","json"}),
     *     @OA\Property(property="period", type="string", enum={"daily","weekly","monthly","annual"}),
     *     @OA\Property(property="from", type="string", format="date"),
     *     @OA\Property(property="to", type="string", format="date")
     *   )),
     *
     *   @OA\Response(response=202, description="Queued — poll the run for completion"),
     *   @OA\Response(response=201, description="Generated inline with a download URL"))
     */
    public function generate(Request $request): JsonResponse
    {
        $data = $request->validate([
            'code' => ['required', 'string', 'exists:report_definitions,code'],
            'format' => ['nullable', 'string', 'in:pdf,xlsx,csv,json'],
            'period' => ['nullable', 'string', 'in:daily,weekly,monthly,annual'],
            'from' => ['nullable', 'date'],
            'to' => ['nullable', 'date', 'after_or_equal:from'],
            'vehicle_id' => ['nullable', 'integer'],
            'fleet_id' => ['nullable', 'integer'],
        ]);

        $run = $this->reports->request(
            $request->user(),
            $data['code'],
            collect($data)->except(['code', 'format'])->all(),
            $data['format'] ?? 'pdf',
        );

        return $run->status === ReportRun::STATUS_COMPLETED
            ? ApiResponse::created($this->present($run), 'Report ready.')
            : ApiResponse::success($this->present($run), 'Report queued.', 202);
    }

    /**
     * @OA\Get(path="/reports/runs", tags={"Reports"}, security={{"bearerAuth":{}}},
     *   summary="Report history", @OA\Response(response=200, description="Runs"))
     */
    public function runs(Request $request): JsonResponse
    {
        /*
         * Presented, not returned raw. The list used to hand back the model as
         * it sits in the database, which differed from what generate() and
         * show() return for the same run — different key names, no download
         * URL — so a client written against one shape broke on the other. It
         * also exposed `file_path`, the internal storage key, which is not the
         * caller's business and is not reachable from a browser anyway.
         */
        $paginator = ReportRun::query()
            ->where('requested_by', $request->user()->getKey())
            ->with('definition:id,code,name')
            ->latest()
            ->paginate(20)
            ->through(fn (ReportRun $run) => $this->present($run));

        return ApiResponse::paginated($paginator);
    }

    /**
     * @OA\Get(path="/reports/runs/{run}", tags={"Reports"}, security={{"bearerAuth":{}}},
     *   summary="Report run status and download link",
     *
     *   @OA\Response(response=200, description="Run with a signed URL when complete"))
     */
    public function show(Request $request, ReportRun $run): JsonResponse
    {
        $this->assertOwns($request, $run);

        return ApiResponse::success($this->present($run));
    }

    /**
     * @OA\Get(path="/reports/runs/{run}/download", tags={"Reports"}, security={{"bearerAuth":{}}},
     *   summary="Download the generated file",
     *
     *   @OA\Response(response=200, description="The file"),
     *   @OA\Response(response=403, description="Generated by someone else"),
     *   @OA\Response(response=404, description="The generated file is gone"),
     *   @OA\Response(response=409, description="Still generating"),
     *   @OA\Response(response=410, description="Past its retention window"))
     */
    public function download(Request $request, ReportRun $run): StreamedResponse
    {
        /*
         * Streamed through the API rather than handed out as a signed storage
         * URL. Two reasons, and the first is the one that bites: object storage
         * signs URLs against the endpoint the *server* uses to reach it, which
         * here is an internal hostname a browser cannot resolve. The second is
         * that a signed URL escapes authorization the moment it is issued —
         * this route re-checks ownership on every request instead.
         */
        $this->assertOwns($request, $run);

        /*
         * DomainException rather than abort(404): the renderer matches
         * NotFoundHttpException before HttpExceptionInterface and replaces the
         * message with "The requested endpoint does not exist", so an expired
         * report told the operator their URL was wrong. These are states of a
         * resource that plainly does exist, and each one says what to do next.
         */
        if ($run->status !== ReportRun::STATUS_COMPLETED || $run->file_path === null) {
            throw new DomainException('That report has not finished generating.', 'report_not_ready', 409);
        }

        // Retention is a promise about how long a file is kept, so an expired
        // run must not serve a file that merely has not been swept up yet.
        if ($run->expires_at !== null && $run->expires_at->isPast()) {
            throw new DomainException('That report has expired. Generate it again.', 'report_expired', 410);
        }

        if (! Storage::exists($run->file_path)) {
            throw new DomainException('The generated file is no longer available.', 'report_file_missing', 404);
        }

        return Storage::download($run->file_path, $this->filename($run));
    }

    /**
     * A name that means something in a downloads folder: the report and the
     * period it covers, rather than the storage key's run id.
     */
    private function filename(ReportRun $run): string
    {
        return sprintf(
            '%s-%s-to-%s.%s',
            $run->definition->code,
            $run->period_start?->toDateString() ?? 'start',
            $run->period_end?->toDateString() ?? 'end',
            $run->format,
        );
    }

    private function assertOwns(Request $request, ReportRun $run): void
    {
        abort_unless(
            $run->requested_by === $request->user()->getKey() || $request->user()->isPlatformAdministrator(),
            403,
            'That report was generated by someone else.',
        );
    }

    private function present(ReportRun $run): array
    {
        return [
            'id' => $run->getKey(),
            'report' => $run->definition?->name,
            'code' => $run->definition?->code,
            'status' => $run->status,
            'format' => $run->format,
            'period' => [
                'from' => $run->period_start?->toDateString(),
                'to' => $run->period_end?->toDateString(),
            ],
            'row_count' => $run->row_count,
            'file_size' => $run->file_size,
            // The API route, not the storage URL — see download() for why.
            'download_url' => $run->status === ReportRun::STATUS_COMPLETED
                ? url("/api/v1/reports/runs/{$run->getKey()}/download")
                : null,
            'error_message' => $run->error_message,
            'completed_at' => $run->completed_at?->toIso8601String(),
        ];
    }
}
